name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']
        dependencies: ['normal', 'authoritative']

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      if: matrix.dependencies == 'normal'
      run: composer install --prefer-dist
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Install dependencies
      if: matrix.dependencies == 'authoritative'
      run: composer install --prefer-dist --classmap-authoritative
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Run the tests
      run: composer run test
